FROM java:8u66-jdk
MAINTAINER zhouling mahal@vip.qq.com
RUN mkdir -p /data/simfight
ADD simfight.jar /data/simfight.jar
ADD simfight/configs/ /data/simfight/configs/
ADD repository/ /data/repository/
WORKDIR /data
